### ISSUE TITLE
Error enriching with multiple measures

### ISSUE THREAD

**Issue by javitonino** [CartoDB/observatory-extension#318]
STR
1. Create a map with a test point in Spain
2. Request population 20 to 24 normalized by total population

![screenshot_20171115_153805](https://user-images.githubusercontent.com/7569673/32841604-1319394e-ca1b-11e7-9200-5f6ef8206bf2.png)

You get this error https://rollbar.com/carto/Dataservices-API/items/236/occurrences/33533030533/

Example .carto; Rename to `.carto` (remove fake `.zip` extension)
[Universidades Madrid (on 2017-11-15 at 14.34.03).carto.zip](https://github.com/CartoDB/observatory-extension/files/1475072/Universidades.Madrid.on.2017-11-15.at.14.34.03.carto.zip)

**Comment by antoniocarlon** [comment]
Tested both in my local environment and staging and it's currently working as expected. I'll give it another try when we deploy the next dump to ensure that the problem is no longer occuring.

Anyway, the rollbar error can be related to https://github.com/CartoDB/observatory-extension/issues/320 so I'll keep an eye on this.

**Comment by javitonino** [comment]
Yes, I'm pretty sure this is related to the different tables thing, it did not happen with other choices for the denominators. You may have fixed it with the changes to some INE denominators and so on. Anyway, this doesn't happen now, so closing it.
